### ISSUE TITLE
simplify export from index

### ISSUE THREAD

**Issue by aneurysmjs** [MacKentoch/react-bootstrap-webpack-starter#17]

**Comment by aneurysmjs** [comment]
instead of this:

```javascript
import MainLayout from './MainLayout';

export default MainLayout;
```

you can do it like this: 

```javascript
export { default }  from './MainLayout';
```

**Comment by MacKentoch** [comment]
Thank you.

I keep my convention since I'm used to use index file to wrap HOC, or when redux, to connect to redux.
And I just prefer the explicit naming 😉.
