### ISSUE TITLE
loadable-components isn't working

### ISSUE THREAD

**Issue by phattanun** [MacKentoch/react-bootstrap-webpack-starter#19]
After running "npm run prod", it produces just 1 app.js and 1 vendor.js. No different from primitive method without loadable-components. This means It's not working at all.

**Comment by MacKentoch** [comment]
Hi,

Yes something's wrong. Investigating.

**Comment by phattanun** [comment]
> Hi,
> 
> Yes something's wrong. Investigating.

I'm really panic when I saw that the combined bundle size is ~800kb out of the box. I'd expect something under 35-70kb at first load.
Thanks btw. Without these problems your starter is great!

**Comment by phattanun** [comment]
this [https://github.com/MacKentoch/react-redux-bootstrap-webpack-starter](url) seems to have the same issue.
