### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by benjyz** [MacKentoch/react-bootstrap-webpack-starter#20]
git clone and then `npm install` and `npm run start`

`ENOENT: no such file or directory, open '/Users/x/react-bootstrap-webpack-starter/package.json'`

npm --version 6.13.4
node --version v12.16.1

**Comment by MacKentoch** [comment]
Sorry I guess I forgot to mention:

- `Front app` is now in `./front` and no more at root.
- `server app` is now in `./server` and no more at root.

This avoids overcomplicated configuration for the toolchain and special for TypeScript.
