### ISSUE TITLE
code source

### ISSUE THREAD

**Issue by fernandooj** [MacKentoch/react-bootstrap-webpack-starter#5]
Hi thanks for your projects have been a great help, a question I previously saw that generated all the html code when I was given the source code of the page in the navegator, but now does not show it, there is a way to show the source code?

regards

**Comment by MacKentoch** [comment]
hi @fernandooj 

Thank you!

I'm not sure to understand your question, do you mean when does react renders all source code to html?
If so it is [here with reactDOM.render](https://github.com/MacKentoch/react-bootstrap-webpack-starter/blob/master/src/app/index.js#L23) to div with id="root" in html

TIP: In Chrome add [react developer tool](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) (from facebook) to see matching source 

But as I I'm not sure to understand I may give you a bad answer.

**Comment by fernandooj** [comment]
look the screen
i mean this when we see the source: in view-source:http://localhost:8082/#/
don't show the html inside the section root, and that is bad for the seo
but i use your proyect in a before commit, and show it
thanks for your help

![image](https://user-images.githubusercontent.com/13096198/30770326-5cdb4cea-9ff3-11e7-8cc2-6cb071468d8c.png)

**Comment by MacKentoch** [comment]
Ok I see.

SEO is achieved by server side rendering since this is a single page application.

It would be the same with an angular SPA or any framework that create/manage content from javascript.

**Comment by MacKentoch** [comment]
An example of server side rendering: [here](https://github.com/MacKentoch/react-bootstrap-webpack-ssr-starter/blob/master/src/server/SSR/src/server.js#L92)

**Comment by fernandooj** [comment]
hey thanks a lot, for your help, that's what I was looking for, one last question this render from the source, does not affect seo

**Comment by MacKentoch** [comment]
It is beyond the scope of this starter.

Let me show you this interesting article about SPA and SEO: [seo-vs-react-is-it-neccessary-to-render-react-pages-in-the-backend](https://medium.freecodecamp.org/seo-vs-react-is-it-neccessary-to-render-react-pages-in-the-backend-74ce5015c0c9).

Happy coding!
