### ISSUE TITLE
Yarn Install Failing

### ISSUE THREAD

**Issue by eugene-zheng0208** [MacKentoch/react-bootstrap-webpack-starter#7]
![image](https://user-images.githubusercontent.com/27918762/36373352-e9f1c8ea-1535-11e8-96c2-c0daea0f4f4f.png)

**Comment by eugene-zheng0208** [comment]
![1](https://user-images.githubusercontent.com/27918762/36373512-61cb62ea-1536-11e8-9327-b2c1654f63fe.png)

**Comment by eugene-zheng0208** [comment]
node version: 9.5.0
yarn: 1.3.2
npm: 5.6.0

**Comment by MacKentoch** [comment]
This looks like environment issues (I assume you were using git bash on windows).

By the way I avoid Node 9.x and always prefer LTS versions of node js.

**Comment by MacKentoch** [comment]
I close since this is environment related.

Open back if I was wrong (I could be, why not?!)
