### ISSUE TITLE
Project not starting up

### ISSUE THREAD

**Issue by sethigoldy** [MacKentoch/react-bootstrap-webpack-starter#8]
I have installed the npm and when I try to run I get the following error:

react-bootstrap-webpack-starter@6.1.0 serve-dev ~/react-bootstrap-webpack-starter
npm run dev && nodemon ./src/server/server.js

react-bootstrap-webpack-starter@6.1.0 predev ~/react-bootstrap-webpack-starter
npm run clean-docs

react-bootstrap-webpack-starter@6.1.0 clean-docs ~/react-bootstrap-webpack-starter
rimraf docs/*

react-bootstrap-webpack-starter@6.1.0 dev ~/react-bootstrap-webpack-starter
rimraf docs/public/assets && cross-env NODE_ENV=dev webpack --config webpack.dev.config.js

(node:25051) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: fc243f1228399a2e497e
Version: webpack 4.16.1
Time: 8144ms
Built at: 07/17/2018 4:26:39 PM
                                                Asset       Size   Chunks             Chunk Names
                        0.fc243f1228399a2e497e.js.map   3.83 KiB        0  [emitted]  
                          app.fc243f1228399a2e497e.js    117 KiB      app  [emitted]  app
                            0.fc243f1228399a2e497e.js   10.6 KiB        0  [emitted]  
                            1.fc243f1228399a2e497e.js   4.41 KiB        1  [emitted]  
                            2.fc243f1228399a2e497e.js   4.69 KiB        2  [emitted]  
                            3.fc243f1228399a2e497e.js   5.15 KiB        3  [emitted]  
                            4.fc243f1228399a2e497e.js   4.99 KiB        4  [emitted]  
                      app.fc243f1228399a2e497e.js.map   78.1 KiB      app  [emitted]  app
                  vendors.fc243f1228399a2e497e.js.map   2.22 MiB  vendors  [emitted]  vendors
                      vendors.fc243f1228399a2e497e.js   2.17 MiB  vendors  [emitted]  vendors
                        1.fc243f1228399a2e497e.js.map   1.36 KiB        1  [emitted]  
                        2.fc243f1228399a2e497e.js.map    1.5 KiB        2  [emitted]  
                        3.fc243f1228399a2e497e.js.map   1.58 KiB        3  [emitted]  
                        4.fc243f1228399a2e497e.js.map   2.69 KiB        4  [emitted]  
                                        ../index.html  882 bytes           [emitted]  
                                  modernizr-bundle.js   5.37 KiB           [emitted]  
precache-manifest.fcf700426a295d74d0af362a58754f1b.js  681 bytes           [emitted]  
                                                sw.js  969 bytes           [emitted]  
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {vendors} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {vendors} [built]
[./src/front/Root.js] 3.28 KiB {app} [built]
[./src/front/contexts/auth/providerComponent/index.js] 4.67 KiB {app} [built]
[./src/front/hoc/withMainLayout/index.js] 78 bytes {app} [built]
[./src/front/hoc/withMainLayout/withMainLayout.js] 5.33 KiB {app} [built]
[./src/front/index.js] 1.73 KiB {app} [built]
[./src/front/pages/about/index.js] 241 bytes {1} [built]
[./src/front/pages/home/index.js] 238 bytes {0} [built]
[./src/front/pages/login/Login.js] 12.7 KiB {app} [built]
[./src/front/pages/login/index.js] 289 bytes {app} [built]
[./src/front/routes/MainRoutes.js] 608 bytes {app} [built]
[./src/front/routes/routes.js] 746 bytes {app} [built]
[./src/front/services/auth/index.js] 8.99 KiB {app} [built]
[./src/front/style/injectGlobalStyles.js] 938 bytes {app} [built]
    + 520 hidden modules
Child html-webpack-plugin for "../index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/front/statics/index.html] 923 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module

react-bootstrap-webpack-starter@6.1.0 postdev ~/react-bootstrap-webpack-starter
react-snap

~/react-bootstrap-webpack-starter/node_modules/react-snap/run.js:9
  ...reactSnap
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 4.4.0-130-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-bootstrap-webpack-starter@6.1.0 postdev: `react-snap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-bootstrap-webpack-starter@6.1.0 postdev script 'react-snap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-bootstrap-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-snap

Please help me with this error.

I also tried the following solution but it won't help:
https://github.com/babel/babel-loader/issues/170

**Comment by MacKentoch** [comment]
hi @sethigoldy 

Sorry to read that.

Is there something preventing you to upgrade your NodeJS to 8.6+? 

If not I strongly suggest you to upgrade (use nvm if you need multiple node js version on same machine).
Like that NodeJS will be able to rest spread without babel (*I suspect your issue comes from here*).

**Comment by MacKentoch** [comment]
Currently finishing upgrading and fixing things like Tappable error because of webpack plugin `extract-text-webpack-plugin@next`. 

`Then I will reinstall from scratch to see what could be wrong

**Comment by sethigoldy** [comment]
Thanks @MacKentoch  It worked
